# Generated by Django 5.0.6 on 2024-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('habitacion', models.CharField(max_length=39)),
                ('personas', models.CharField(max_length=2)),
            ],
        ),
    ]
