# Generated by Django 5.0.6 on 2024-06-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_habitacion', models.CharField(choices=[('Lujosa', 'Lujosa'), ('Premium', 'Premium'), ('Clasica', 'Clasica')], max_length=20)),
                ('numero_visitantes', models.PositiveIntegerField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
