# Generated by Django 5.0.6 on 2024-06-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranum', '0002_reservation_delete_reservas'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('numero_visitantes', models.PositiveIntegerField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('total', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_habitacion',
            fields=[
                ('id_habitacion', models.AutoField(db_column='idHabitacion', primary_key=True, serialize=False)),
                ('habitacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
