# Generated by Django 5.0.6 on 2024-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranum', '0004_reserva_id_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_habitacion',
            name='valor',
            field=models.IntegerField(default=234),
            preserve_default=False,
        ),
    ]
