# Generated by Django 5.0.6 on 2024-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranum', '0005_tipo_habitacion_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('contrasenia', models.CharField(max_length=128)),
            ],
        ),
    ]
